### ISSUE TITLE
Getting data

### ISSUE THREAD

**Issue by sturlahallas** [suhajdab/verisure-api#5]
Hi. I'm crap with javascript, so if possible, could you in some way show or point me in a direction as how to get data from your functions? Preferably in a LAMP-stack? A simple php-script to get the json from your script would be brilliant. And a short set up description maybe? :-) Pretty please? I would like to incorporate your code in my home automation site, but can't for the life of me figure out how to get the data I need from your api.

Thanks in advance!
Sturla Hallas -> void(null)

**Comment by suhajdab** [comment]
Hi! This is meant to be used in nodejs. I'm sure the requests would be easy to implement in php too, but I have no intention of going that way.
